name: expense_tracker_client
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.1
  http: ^1.2.2
  image_picker: ^1.0.6
  flutter_lints: ^2.0.0
  provider: ^5.0.0
  path: ^1.0.0
  sqflite: ^2.0.0
  web_socket_channel: ^2.1.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  connectivity_plus: ^4.0.0

  # IOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true