# Automatically generated by Pynguin.
import main as module_0


def test_case_0():
    try:
        str_0 = None
        calculator_0 = module_0.Calculator()
        dict_0 = {str_0: str_0, str_0: calculator_0, str_0: str_0}
        calculator_1 = module_0.Calculator(**dict_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = ':)'
        bytes_0 = b'\x82u\xf5\xd7d+\xbfq\x98\x81\x95\xad\xb8'
        calculator_0 = module_0.Calculator()
        var_0 = calculator_0.add(str_0, bytes_0)
    except BaseException:
        pass


def test_case_2():
    try:
        bytes_0 = b'Z'
        tuple_0 = bytes_0,
        bool_0 = False
        calculator_0 = module_0.Calculator()
        var_0 = calculator_0.subtract(tuple_0, bool_0)
    except BaseException:
        pass


def test_case_3():
    try:
        int_0 = None
        dict_0 = {}
        list_0 = [int_0, dict_0]
        list_1 = [list_0, list_0, int_0, int_0]
        list_2 = []
        calculator_0 = module_0.Calculator(*list_2)
        var_0 = calculator_0.multiply(list_0, list_1)
    except BaseException:
        pass
