# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ve2UWk6VejV4YrB843tfhlNfo-Ozg-34
"""

from transformers import pipeline
MODEL = "jy46604790/Fake-News-Bert-Detect"
clf = pipeline("text-classification", model=MODEL, tokenizer=MODEL)

# Input text
text_true = "Pretul companiei Hidroelectrica a crescut fata de cel de la listare"

text_fake = "Trump said that US would attack Russia if he becomes president"

# Get the classification result
result_true = clf(text_true)
result_fake = clf(text_fake)

# Extract the label from the result (it will be a list of dictionaries)
label1 = result_true[0]['label']  # Get the label from the first result
label2 = result_fake[0]['label']  # Get the label from the second result

# Print the result based on the label (LABEL_1 real and LABEL_0 for fake)
print(f"First news paragraph is a {'Real' if label1 == 'LABEL_1' else 'Fake'} one")
print(f"Second news paragraph is a {'Real' if label2 == 'LABEL_1' else 'Fake'} one")

